/**
 * Machine Purchase / Financing / Location Services Agreement
 *
 * Generated by buildMachineAgreement() at order submission time and
 * snapshotted onto machine_orders.agreement_text so the exact language
 * the customer saw is preserved even if this file is later edited.
 */

export const MACHINE_AGREEMENT_VERSION = "v1.0";

export interface MachineAgreementInput {
  customerName: string;
  companyName: string | null;
  machineName: string;
  quantity: number;
  unitPriceCents: number;
  subtotalCents: number;
  purchaseType: "cash" | "finance";
  financingRequested: boolean;
  estimatedMonthlyCents: number | null;
  financingTermYears: number;
  financingRateLabel: string;
  locationServicesSelected: boolean;
  locationServicesMinCents: number | null;
  locationServicesMaxCents: number | null;
}

function formatMoney(cents: number): string {
  return `$${(cents / 100).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

export function buildMachineAgreement(input: MachineAgreementInput): string {
  const {
    customerName,
    companyName,
    machineName,
    quantity,
    unitPriceCents,
    subtotalCents,
    purchaseType,
    financingRequested,
    estimatedMonthlyCents,
    financingTermYears,
    financingRateLabel,
    locationServicesSelected,
    locationServicesMinCents,
    locationServicesMaxCents,
  } = input;

  const buyerLine = companyName
    ? `${customerName} (${companyName})`
    : customerName;

  const financingBlock = financingRequested
    ? `
4. Financing Option (Requested)
Buyer has indicated interest in financing the above purchase. Financing is subject to credit approval and is arranged through Apex AI Vending's third-party financing partners. The estimated monthly payment of ${
        estimatedMonthlyCents ? formatMoney(estimatedMonthlyCents) : "TBD"
      }/machine over ${financingTermYears} years at approximately ${financingRateLabel} is provided for illustrative purposes only and does not constitute a loan offer or approval. Final terms, rates, and monthly payments will be determined by the lender after a credit review and will be documented in a separate financing agreement that Buyer must sign before any machine is shipped. Buyer may withdraw the financing application at any time before signing the financing agreement.`
    : `
4. Cash Purchase
Buyer has elected to pay the full purchase price in cash/wire/ACH. A deposit or full payment instructions will be sent to Buyer under separate cover after Apex AI Vending reviews and approves this order.`;

  const locationServicesBlock = locationServicesSelected
    ? `
5. Location Services Bundle (Selected)
Buyer has elected to bundle Apex AI Vending's location placement services with this order. Location services are billed separately and range from ${
        locationServicesMinCents ? formatMoney(locationServicesMinCents) : "$300.00"
      } to ${
        locationServicesMaxCents ? formatMoney(locationServicesMaxCents) : "$1,200.00"
      } depending on market, placement difficulty, and contract duration. The exact location services fee will be quoted to Buyer before any location work begins and will be documented in a separate location services engagement letter. Buyer is not obligated to accept the final location services quote and may decline without impacting the machine purchase.`
    : "";

  return `Machine Purchase Order & Bundle Agreement

Company:
Apex AI Vending
Fulfillment partner: ByteBite Vending LLC DBA Vending Connector

Agreement Version: ${MACHINE_AGREEMENT_VERSION}
Date: ${new Date().toISOString().slice(0, 10)}

Buyer: ${buyerLine}

1. Order Summary
Buyer is placing an order for the following equipment:
  - Machine: ${machineName}
  - Quantity: ${quantity}
  - Unit Price: ${formatMoney(unitPriceCents)}
  - Subtotal: ${formatMoney(subtotalCents)}
  - Purchase Type: ${purchaseType === "finance" ? "Finance (subject to approval)" : "Cash"}
  - Location Services: ${locationServicesSelected ? "Requested" : "Not requested"}

2. Nature of Transaction
This document is a non-binding purchase order and acknowledgement of terms. Apex AI Vending is the vendor of record for all machine orders placed through Vending Connector. The order is subject to review and acceptance by Apex AI Vending before any fulfillment, delivery, or financing activity begins.

3. No Guarantee / As-Is Sale of Goods
All machines are sold as-is, with all manufacturer warranties assigned to Buyer at the time of delivery. Apex AI Vending makes no independent representation or warranty beyond the manufacturer's warranty. Apex AI Vending does not guarantee specific revenue, throughput, or profitability.
${financingBlock}
${locationServicesBlock}

6. Acceptable Use
Buyer agrees to use the machines in compliance with all applicable federal, state, and local laws, including health, tax, and labor laws. Buyer will not resell leads, contact information, or placement opportunities obtained through any bundled services.

7. Limitation of Liability
Apex AI Vending and Vending Connector are not liable for lost revenue, missed opportunities, equipment downtime, third-party financing decisions, or consequential damages of any kind. Total liability is limited to amounts actually paid to Apex AI Vending under this order.

8. Refunds & Cancellation
Before Apex AI Vending ships any machine or begins any location services work, Buyer may cancel this order at no cost by emailing james@apexaivending.com. Once equipment has shipped or location services work has started, refunds and cancellations are governed by the separate machine purchase contract and location services engagement letter Buyer will sign before work begins.

9. Next Steps
After Buyer submits this order, Apex AI Vending will contact Buyer by email or phone to:
  (a) confirm order details,
  (b) send payment or financing application instructions (as applicable),
  (c) send the location services engagement letter (if selected), and
  (d) schedule delivery and installation.

10. Agreement Acceptance
By clicking "Submit Order", Buyer acknowledges that Buyer has read and understood this Agreement, that the order summary above is correct, and that any binding financing, location services, or equipment contracts will require a separate signature before any funds are collected or work is performed. This document is an order form and expression of intent, not a final contract of sale.

— End of Agreement —`;
}
